-- 너무 어렵다...RECURSIVE 다시 공부해보기
WITH RECURSIVE HOURS AS(
    SELECT 0 AS N
    UNION ALL
    SELECT N + 1 FROM HOURS
    WHERE N < 23)

SELECT HOURS.N AS HOUR, IFNULL(COUNT(A.DATETIME), 0) AS COUNT
FROM HOURS 
LEFT JOIN ANIMAL_OUTS A ON HOUR(A.DATETIME) = HOURS.N
GROUP BY HOURS.N
ORDER BY HOURS.N